---

- hosts: all
  become: true
  tasks:

  - name: create a user
    user:
      name: simone
      groups: root

  - name: add ssh key to simone
    authorized_key:
      user: simone
      key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIASjfqScfc64sIn5t3VcYsWgB+jiNIYclbaYndgVBzWZ ansible"

  - name: add sudoers file for simone
    copy:
      src: sudoer_simone
      dest: /etc/sudoers.d/simone
      owner: root
      group: root
      mode: 0440
