---

- hosts: all
  become: true
  tasks:

  - name: install apache2 and php packages for Ubuntu & update the cache
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
      update_cache: yes
    when : ansible_distribution == "Ubuntu"

