---

- hosts: all
  become: true
  tasks:

  - name: install apache2 and php
    package:
      name:
        - "{{ apache_package}}"
        - "{{ php_package}}"
      state: latest
      update_cache: yes


#we should add those vars to the inventory file --->
#package means that if we are in centOS its gonna use yum and Ubuntu gonna use apt
