---

- hosts: all
  become: true
  tasks:

  - name: start apache
    tags: apache,apache2
    service:
      name: apache2
      state: started
      enabled: yes
    when: ansible_distribution == "Ubuntu"

  - name: change email in a conf file
    lineinfile:
      path: /test/test.conf
      regexp: '^email'
      line: email youssefkhalifi767@gmail.com
    when: ansible_distribution == "Ubuntu"
    register: change

  - name: restart apache2
    service:
      name: apache2
      state: restarted
    when: change.changed
